// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "MonsterStuff.pb.h"
#import "SharedEnumConfig.pb.h"
#import "Task.pb.h"
#import "User.pb.h"

@class BeginDungeonRequestProto;
@class BeginDungeonRequestProto_Builder;
@class BeginDungeonResponseProto;
@class BeginDungeonResponseProto_Builder;
@class EndDungeonRequestProto;
@class EndDungeonRequestProto_Builder;
@class EndDungeonResponseProto;
@class EndDungeonResponseProto_Builder;
@class FullTaskProto;
@class FullTaskProto_Builder;
@class FullUserMonsterProto;
@class FullUserMonsterProto_Builder;
@class FullUserProto;
@class FullUserProto_Builder;
@class MinimumClanProto;
@class MinimumClanProto_Builder;
@class MinimumUserMonsterProto;
@class MinimumUserMonsterProto_Builder;
@class MinimumUserMonsterSellProto;
@class MinimumUserMonsterSellProto_Builder;
@class MinimumUserProto;
@class MinimumUserProtoWithFacebookId;
@class MinimumUserProtoWithFacebookId_Builder;
@class MinimumUserProtoWithLevel;
@class MinimumUserProtoWithLevel_Builder;
@class MinimumUserProtoWithMaxResources;
@class MinimumUserProtoWithMaxResources_Builder;
@class MinimumUserProto_Builder;
@class MinimumUserTaskProto;
@class MinimumUserTaskProto_Builder;
@class MonsterBattleDialogueProto;
@class MonsterBattleDialogueProto_Builder;
@class MonsterLevelInfoProto;
@class MonsterLevelInfoProto_Builder;
@class MonsterProto;
@class MonsterProto_Builder;
@class PersistentEventProto;
@class PersistentEventProto_Builder;
@class ReviveInDungeonRequestProto;
@class ReviveInDungeonRequestProto_Builder;
@class ReviveInDungeonResponseProto;
@class ReviveInDungeonResponseProto_Builder;
@class StaticUserLevelInfoProto;
@class StaticUserLevelInfoProto_Builder;
@class TaskStageMonsterProto;
@class TaskStageMonsterProto_Builder;
@class TaskStageProto;
@class TaskStageProto_Builder;
@class UserCurrentMonsterTeamProto;
@class UserCurrentMonsterTeamProto_Builder;
@class UserEnhancementItemProto;
@class UserEnhancementItemProto_Builder;
@class UserEnhancementProto;
@class UserEnhancementProto_Builder;
@class UserFacebookInviteForSlotProto;
@class UserFacebookInviteForSlotProto_Builder;
@class UserMonsterCurrentExpProto;
@class UserMonsterCurrentExpProto_Builder;
@class UserMonsterCurrentHealthProto;
@class UserMonsterCurrentHealthProto_Builder;
@class UserMonsterEvolutionProto;
@class UserMonsterEvolutionProto_Builder;
@class UserMonsterHealingProto;
@class UserMonsterHealingProto_Builder;
@class UserPersistentEventProto;
@class UserPersistentEventProto_Builder;
@class UserPvpLeagueProto;
@class UserPvpLeagueProto_Builder;
typedef enum {
  BeginDungeonResponseProto_BeginDungeonStatusSuccess = 1,
  BeginDungeonResponseProto_BeginDungeonStatusFailOther = 2,
} BeginDungeonResponseProto_BeginDungeonStatus;

BOOL BeginDungeonResponseProto_BeginDungeonStatusIsValidValue(BeginDungeonResponseProto_BeginDungeonStatus value);

typedef enum {
  EndDungeonResponseProto_EndDungeonStatusSuccess = 1,
  EndDungeonResponseProto_EndDungeonStatusFailOther = 2,
} EndDungeonResponseProto_EndDungeonStatus;

BOOL EndDungeonResponseProto_EndDungeonStatusIsValidValue(EndDungeonResponseProto_EndDungeonStatus value);

typedef enum {
  ReviveInDungeonResponseProto_ReviveInDungeonStatusSuccess = 1,
  ReviveInDungeonResponseProto_ReviveInDungeonStatusFailInsufficientFunds = 2,
  ReviveInDungeonResponseProto_ReviveInDungeonStatusFailOther = 3,
} ReviveInDungeonResponseProto_ReviveInDungeonStatus;

BOOL ReviveInDungeonResponseProto_ReviveInDungeonStatusIsValidValue(ReviveInDungeonResponseProto_ReviveInDungeonStatus value);


@interface EventDungeonRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface BeginDungeonRequestProto : PBGeneratedMessage {
@private
  BOOL hasUserBeatAllCityTasks_:1;
  BOOL hasIsEvent_:1;
  BOOL hasForceEnemyElem_:1;
  BOOL hasClientTime_:1;
  BOOL hasTaskId_:1;
  BOOL hasPersistentEventId_:1;
  BOOL hasGemsSpent_:1;
  BOOL hasSender_:1;
  BOOL hasElem_:1;
  BOOL userBeatAllCityTasks_:1;
  BOOL isEvent_:1;
  BOOL forceEnemyElem_:1;
  int64_t clientTime;
  int32_t taskId;
  int32_t persistentEventId;
  int32_t gemsSpent;
  MinimumUserProto* sender;
  Element elem;
  NSMutableArray* mutableQuestIdsList;
}
- (BOOL) hasSender;
- (BOOL) hasClientTime;
- (BOOL) hasTaskId;
- (BOOL) hasUserBeatAllCityTasks;
- (BOOL) hasIsEvent;
- (BOOL) hasPersistentEventId;
- (BOOL) hasGemsSpent;
- (BOOL) hasElem;
- (BOOL) hasForceEnemyElem;
@property (readonly, retain) MinimumUserProto* sender;
@property (readonly) int64_t clientTime;
@property (readonly) int32_t taskId;
- (BOOL) userBeatAllCityTasks;
- (BOOL) isEvent;
@property (readonly) int32_t persistentEventId;
@property (readonly) int32_t gemsSpent;
@property (readonly) Element elem;
- (BOOL) forceEnemyElem;
- (NSArray*) questIdsList;
- (int32_t) questIdsAtIndex:(int32_t) index;

+ (BeginDungeonRequestProto*) defaultInstance;
- (BeginDungeonRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BeginDungeonRequestProto_Builder*) builder;
+ (BeginDungeonRequestProto_Builder*) builder;
+ (BeginDungeonRequestProto_Builder*) builderWithPrototype:(BeginDungeonRequestProto*) prototype;

+ (BeginDungeonRequestProto*) parseFromData:(NSData*) data;
+ (BeginDungeonRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BeginDungeonRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (BeginDungeonRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BeginDungeonRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BeginDungeonRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BeginDungeonRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  BeginDungeonRequestProto* result;
}

- (BeginDungeonRequestProto*) defaultInstance;

- (BeginDungeonRequestProto_Builder*) clear;
- (BeginDungeonRequestProto_Builder*) clone;

- (BeginDungeonRequestProto*) build;
- (BeginDungeonRequestProto*) buildPartial;

- (BeginDungeonRequestProto_Builder*) mergeFrom:(BeginDungeonRequestProto*) other;
- (BeginDungeonRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BeginDungeonRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (BeginDungeonRequestProto_Builder*) setSender:(MinimumUserProto*) value;
- (BeginDungeonRequestProto_Builder*) setSenderBuilder:(MinimumUserProto_Builder*) builderForValue;
- (BeginDungeonRequestProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (BeginDungeonRequestProto_Builder*) clearSender;

- (BOOL) hasClientTime;
- (int64_t) clientTime;
- (BeginDungeonRequestProto_Builder*) setClientTime:(int64_t) value;
- (BeginDungeonRequestProto_Builder*) clearClientTime;

- (BOOL) hasTaskId;
- (int32_t) taskId;
- (BeginDungeonRequestProto_Builder*) setTaskId:(int32_t) value;
- (BeginDungeonRequestProto_Builder*) clearTaskId;

- (BOOL) hasUserBeatAllCityTasks;
- (BOOL) userBeatAllCityTasks;
- (BeginDungeonRequestProto_Builder*) setUserBeatAllCityTasks:(BOOL) value;
- (BeginDungeonRequestProto_Builder*) clearUserBeatAllCityTasks;

- (BOOL) hasIsEvent;
- (BOOL) isEvent;
- (BeginDungeonRequestProto_Builder*) setIsEvent:(BOOL) value;
- (BeginDungeonRequestProto_Builder*) clearIsEvent;

- (BOOL) hasPersistentEventId;
- (int32_t) persistentEventId;
- (BeginDungeonRequestProto_Builder*) setPersistentEventId:(int32_t) value;
- (BeginDungeonRequestProto_Builder*) clearPersistentEventId;

- (BOOL) hasGemsSpent;
- (int32_t) gemsSpent;
- (BeginDungeonRequestProto_Builder*) setGemsSpent:(int32_t) value;
- (BeginDungeonRequestProto_Builder*) clearGemsSpent;

- (NSArray*) questIdsList;
- (int32_t) questIdsAtIndex:(int32_t) index;
- (BeginDungeonRequestProto_Builder*) replaceQuestIdsAtIndex:(int32_t) index with:(int32_t) value;
- (BeginDungeonRequestProto_Builder*) addQuestIds:(int32_t) value;
- (BeginDungeonRequestProto_Builder*) addAllQuestIds:(NSArray*) values;
- (BeginDungeonRequestProto_Builder*) clearQuestIdsList;

- (BOOL) hasElem;
- (Element) elem;
- (BeginDungeonRequestProto_Builder*) setElem:(Element) value;
- (BeginDungeonRequestProto_Builder*) clearElem;

- (BOOL) hasForceEnemyElem;
- (BOOL) forceEnemyElem;
- (BeginDungeonRequestProto_Builder*) setForceEnemyElem:(BOOL) value;
- (BeginDungeonRequestProto_Builder*) clearForceEnemyElem;
@end

@interface BeginDungeonResponseProto : PBGeneratedMessage {
@private
  BOOL hasUserTaskId_:1;
  BOOL hasTaskId_:1;
  BOOL hasSender_:1;
  BOOL hasStatus_:1;
  int64_t userTaskId;
  int32_t taskId;
  MinimumUserProto* sender;
  BeginDungeonResponseProto_BeginDungeonStatus status;
  NSMutableArray* mutableTspList;
}
- (BOOL) hasSender;
- (BOOL) hasUserTaskId;
- (BOOL) hasTaskId;
- (BOOL) hasStatus;
@property (readonly, retain) MinimumUserProto* sender;
@property (readonly) int64_t userTaskId;
@property (readonly) int32_t taskId;
@property (readonly) BeginDungeonResponseProto_BeginDungeonStatus status;
- (NSArray*) tspList;
- (TaskStageProto*) tspAtIndex:(int32_t) index;

+ (BeginDungeonResponseProto*) defaultInstance;
- (BeginDungeonResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BeginDungeonResponseProto_Builder*) builder;
+ (BeginDungeonResponseProto_Builder*) builder;
+ (BeginDungeonResponseProto_Builder*) builderWithPrototype:(BeginDungeonResponseProto*) prototype;

+ (BeginDungeonResponseProto*) parseFromData:(NSData*) data;
+ (BeginDungeonResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BeginDungeonResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (BeginDungeonResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BeginDungeonResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BeginDungeonResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BeginDungeonResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  BeginDungeonResponseProto* result;
}

- (BeginDungeonResponseProto*) defaultInstance;

- (BeginDungeonResponseProto_Builder*) clear;
- (BeginDungeonResponseProto_Builder*) clone;

- (BeginDungeonResponseProto*) build;
- (BeginDungeonResponseProto*) buildPartial;

- (BeginDungeonResponseProto_Builder*) mergeFrom:(BeginDungeonResponseProto*) other;
- (BeginDungeonResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BeginDungeonResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (BeginDungeonResponseProto_Builder*) setSender:(MinimumUserProto*) value;
- (BeginDungeonResponseProto_Builder*) setSenderBuilder:(MinimumUserProto_Builder*) builderForValue;
- (BeginDungeonResponseProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (BeginDungeonResponseProto_Builder*) clearSender;

- (NSArray*) tspList;
- (TaskStageProto*) tspAtIndex:(int32_t) index;
- (BeginDungeonResponseProto_Builder*) replaceTspAtIndex:(int32_t) index with:(TaskStageProto*) value;
- (BeginDungeonResponseProto_Builder*) addTsp:(TaskStageProto*) value;
- (BeginDungeonResponseProto_Builder*) addAllTsp:(NSArray*) values;
- (BeginDungeonResponseProto_Builder*) clearTspList;

- (BOOL) hasUserTaskId;
- (int64_t) userTaskId;
- (BeginDungeonResponseProto_Builder*) setUserTaskId:(int64_t) value;
- (BeginDungeonResponseProto_Builder*) clearUserTaskId;

- (BOOL) hasTaskId;
- (int32_t) taskId;
- (BeginDungeonResponseProto_Builder*) setTaskId:(int32_t) value;
- (BeginDungeonResponseProto_Builder*) clearTaskId;

- (BOOL) hasStatus;
- (BeginDungeonResponseProto_BeginDungeonStatus) status;
- (BeginDungeonResponseProto_Builder*) setStatus:(BeginDungeonResponseProto_BeginDungeonStatus) value;
- (BeginDungeonResponseProto_Builder*) clearStatus;
@end

@interface EndDungeonRequestProto : PBGeneratedMessage {
@private
  BOOL hasUserWon_:1;
  BOOL hasFirstTimeUserWonTask_:1;
  BOOL hasUserBeatAllCityTasks_:1;
  BOOL hasUserTaskId_:1;
  BOOL hasClientTime_:1;
  BOOL hasSender_:1;
  BOOL userWon_:1;
  BOOL firstTimeUserWonTask_:1;
  BOOL userBeatAllCityTasks_:1;
  int64_t userTaskId;
  int64_t clientTime;
  MinimumUserProtoWithMaxResources* sender;
}
- (BOOL) hasSender;
- (BOOL) hasUserTaskId;
- (BOOL) hasUserWon;
- (BOOL) hasClientTime;
- (BOOL) hasFirstTimeUserWonTask;
- (BOOL) hasUserBeatAllCityTasks;
@property (readonly, retain) MinimumUserProtoWithMaxResources* sender;
@property (readonly) int64_t userTaskId;
- (BOOL) userWon;
@property (readonly) int64_t clientTime;
- (BOOL) firstTimeUserWonTask;
- (BOOL) userBeatAllCityTasks;

+ (EndDungeonRequestProto*) defaultInstance;
- (EndDungeonRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EndDungeonRequestProto_Builder*) builder;
+ (EndDungeonRequestProto_Builder*) builder;
+ (EndDungeonRequestProto_Builder*) builderWithPrototype:(EndDungeonRequestProto*) prototype;

+ (EndDungeonRequestProto*) parseFromData:(NSData*) data;
+ (EndDungeonRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EndDungeonRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (EndDungeonRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EndDungeonRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EndDungeonRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EndDungeonRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  EndDungeonRequestProto* result;
}

- (EndDungeonRequestProto*) defaultInstance;

- (EndDungeonRequestProto_Builder*) clear;
- (EndDungeonRequestProto_Builder*) clone;

- (EndDungeonRequestProto*) build;
- (EndDungeonRequestProto*) buildPartial;

- (EndDungeonRequestProto_Builder*) mergeFrom:(EndDungeonRequestProto*) other;
- (EndDungeonRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EndDungeonRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProtoWithMaxResources*) sender;
- (EndDungeonRequestProto_Builder*) setSender:(MinimumUserProtoWithMaxResources*) value;
- (EndDungeonRequestProto_Builder*) setSenderBuilder:(MinimumUserProtoWithMaxResources_Builder*) builderForValue;
- (EndDungeonRequestProto_Builder*) mergeSender:(MinimumUserProtoWithMaxResources*) value;
- (EndDungeonRequestProto_Builder*) clearSender;

- (BOOL) hasUserTaskId;
- (int64_t) userTaskId;
- (EndDungeonRequestProto_Builder*) setUserTaskId:(int64_t) value;
- (EndDungeonRequestProto_Builder*) clearUserTaskId;

- (BOOL) hasUserWon;
- (BOOL) userWon;
- (EndDungeonRequestProto_Builder*) setUserWon:(BOOL) value;
- (EndDungeonRequestProto_Builder*) clearUserWon;

- (BOOL) hasClientTime;
- (int64_t) clientTime;
- (EndDungeonRequestProto_Builder*) setClientTime:(int64_t) value;
- (EndDungeonRequestProto_Builder*) clearClientTime;

- (BOOL) hasFirstTimeUserWonTask;
- (BOOL) firstTimeUserWonTask;
- (EndDungeonRequestProto_Builder*) setFirstTimeUserWonTask:(BOOL) value;
- (EndDungeonRequestProto_Builder*) clearFirstTimeUserWonTask;

- (BOOL) hasUserBeatAllCityTasks;
- (BOOL) userBeatAllCityTasks;
- (EndDungeonRequestProto_Builder*) setUserBeatAllCityTasks:(BOOL) value;
- (EndDungeonRequestProto_Builder*) clearUserBeatAllCityTasks;
@end

@interface EndDungeonResponseProto : PBGeneratedMessage {
@private
  BOOL hasUserWon_:1;
  BOOL hasTaskId_:1;
  BOOL hasSender_:1;
  BOOL hasStatus_:1;
  BOOL userWon_:1;
  int32_t taskId;
  MinimumUserProtoWithMaxResources* sender;
  EndDungeonResponseProto_EndDungeonStatus status;
  NSMutableArray* mutableUpdatedOrNewList;
}
- (BOOL) hasSender;
- (BOOL) hasStatus;
- (BOOL) hasTaskId;
- (BOOL) hasUserWon;
@property (readonly, retain) MinimumUserProtoWithMaxResources* sender;
@property (readonly) EndDungeonResponseProto_EndDungeonStatus status;
@property (readonly) int32_t taskId;
- (BOOL) userWon;
- (NSArray*) updatedOrNewList;
- (FullUserMonsterProto*) updatedOrNewAtIndex:(int32_t) index;

+ (EndDungeonResponseProto*) defaultInstance;
- (EndDungeonResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EndDungeonResponseProto_Builder*) builder;
+ (EndDungeonResponseProto_Builder*) builder;
+ (EndDungeonResponseProto_Builder*) builderWithPrototype:(EndDungeonResponseProto*) prototype;

+ (EndDungeonResponseProto*) parseFromData:(NSData*) data;
+ (EndDungeonResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EndDungeonResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (EndDungeonResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EndDungeonResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EndDungeonResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EndDungeonResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  EndDungeonResponseProto* result;
}

- (EndDungeonResponseProto*) defaultInstance;

- (EndDungeonResponseProto_Builder*) clear;
- (EndDungeonResponseProto_Builder*) clone;

- (EndDungeonResponseProto*) build;
- (EndDungeonResponseProto*) buildPartial;

- (EndDungeonResponseProto_Builder*) mergeFrom:(EndDungeonResponseProto*) other;
- (EndDungeonResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EndDungeonResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProtoWithMaxResources*) sender;
- (EndDungeonResponseProto_Builder*) setSender:(MinimumUserProtoWithMaxResources*) value;
- (EndDungeonResponseProto_Builder*) setSenderBuilder:(MinimumUserProtoWithMaxResources_Builder*) builderForValue;
- (EndDungeonResponseProto_Builder*) mergeSender:(MinimumUserProtoWithMaxResources*) value;
- (EndDungeonResponseProto_Builder*) clearSender;

- (BOOL) hasStatus;
- (EndDungeonResponseProto_EndDungeonStatus) status;
- (EndDungeonResponseProto_Builder*) setStatus:(EndDungeonResponseProto_EndDungeonStatus) value;
- (EndDungeonResponseProto_Builder*) clearStatus;

- (NSArray*) updatedOrNewList;
- (FullUserMonsterProto*) updatedOrNewAtIndex:(int32_t) index;
- (EndDungeonResponseProto_Builder*) replaceUpdatedOrNewAtIndex:(int32_t) index with:(FullUserMonsterProto*) value;
- (EndDungeonResponseProto_Builder*) addUpdatedOrNew:(FullUserMonsterProto*) value;
- (EndDungeonResponseProto_Builder*) addAllUpdatedOrNew:(NSArray*) values;
- (EndDungeonResponseProto_Builder*) clearUpdatedOrNewList;

- (BOOL) hasTaskId;
- (int32_t) taskId;
- (EndDungeonResponseProto_Builder*) setTaskId:(int32_t) value;
- (EndDungeonResponseProto_Builder*) clearTaskId;

- (BOOL) hasUserWon;
- (BOOL) userWon;
- (EndDungeonResponseProto_Builder*) setUserWon:(BOOL) value;
- (EndDungeonResponseProto_Builder*) clearUserWon;
@end

@interface ReviveInDungeonRequestProto : PBGeneratedMessage {
@private
  BOOL hasUserTaskId_:1;
  BOOL hasClientTime_:1;
  BOOL hasGemsSpent_:1;
  BOOL hasSender_:1;
  int64_t userTaskId;
  int64_t clientTime;
  int32_t gemsSpent;
  MinimumUserProto* sender;
  NSMutableArray* mutableReviveMeList;
}
- (BOOL) hasSender;
- (BOOL) hasUserTaskId;
- (BOOL) hasClientTime;
- (BOOL) hasGemsSpent;
@property (readonly, retain) MinimumUserProto* sender;
@property (readonly) int64_t userTaskId;
@property (readonly) int64_t clientTime;
@property (readonly) int32_t gemsSpent;
- (NSArray*) reviveMeList;
- (UserMonsterCurrentHealthProto*) reviveMeAtIndex:(int32_t) index;

+ (ReviveInDungeonRequestProto*) defaultInstance;
- (ReviveInDungeonRequestProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReviveInDungeonRequestProto_Builder*) builder;
+ (ReviveInDungeonRequestProto_Builder*) builder;
+ (ReviveInDungeonRequestProto_Builder*) builderWithPrototype:(ReviveInDungeonRequestProto*) prototype;

+ (ReviveInDungeonRequestProto*) parseFromData:(NSData*) data;
+ (ReviveInDungeonRequestProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReviveInDungeonRequestProto*) parseFromInputStream:(NSInputStream*) input;
+ (ReviveInDungeonRequestProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReviveInDungeonRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReviveInDungeonRequestProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReviveInDungeonRequestProto_Builder : PBGeneratedMessage_Builder {
@private
  ReviveInDungeonRequestProto* result;
}

- (ReviveInDungeonRequestProto*) defaultInstance;

- (ReviveInDungeonRequestProto_Builder*) clear;
- (ReviveInDungeonRequestProto_Builder*) clone;

- (ReviveInDungeonRequestProto*) build;
- (ReviveInDungeonRequestProto*) buildPartial;

- (ReviveInDungeonRequestProto_Builder*) mergeFrom:(ReviveInDungeonRequestProto*) other;
- (ReviveInDungeonRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReviveInDungeonRequestProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (ReviveInDungeonRequestProto_Builder*) setSender:(MinimumUserProto*) value;
- (ReviveInDungeonRequestProto_Builder*) setSenderBuilder:(MinimumUserProto_Builder*) builderForValue;
- (ReviveInDungeonRequestProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (ReviveInDungeonRequestProto_Builder*) clearSender;

- (BOOL) hasUserTaskId;
- (int64_t) userTaskId;
- (ReviveInDungeonRequestProto_Builder*) setUserTaskId:(int64_t) value;
- (ReviveInDungeonRequestProto_Builder*) clearUserTaskId;

- (BOOL) hasClientTime;
- (int64_t) clientTime;
- (ReviveInDungeonRequestProto_Builder*) setClientTime:(int64_t) value;
- (ReviveInDungeonRequestProto_Builder*) clearClientTime;

- (NSArray*) reviveMeList;
- (UserMonsterCurrentHealthProto*) reviveMeAtIndex:(int32_t) index;
- (ReviveInDungeonRequestProto_Builder*) replaceReviveMeAtIndex:(int32_t) index with:(UserMonsterCurrentHealthProto*) value;
- (ReviveInDungeonRequestProto_Builder*) addReviveMe:(UserMonsterCurrentHealthProto*) value;
- (ReviveInDungeonRequestProto_Builder*) addAllReviveMe:(NSArray*) values;
- (ReviveInDungeonRequestProto_Builder*) clearReviveMeList;

- (BOOL) hasGemsSpent;
- (int32_t) gemsSpent;
- (ReviveInDungeonRequestProto_Builder*) setGemsSpent:(int32_t) value;
- (ReviveInDungeonRequestProto_Builder*) clearGemsSpent;
@end

@interface ReviveInDungeonResponseProto : PBGeneratedMessage {
@private
  BOOL hasSender_:1;
  BOOL hasStatus_:1;
  MinimumUserProto* sender;
  ReviveInDungeonResponseProto_ReviveInDungeonStatus status;
}
- (BOOL) hasSender;
- (BOOL) hasStatus;
@property (readonly, retain) MinimumUserProto* sender;
@property (readonly) ReviveInDungeonResponseProto_ReviveInDungeonStatus status;

+ (ReviveInDungeonResponseProto*) defaultInstance;
- (ReviveInDungeonResponseProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReviveInDungeonResponseProto_Builder*) builder;
+ (ReviveInDungeonResponseProto_Builder*) builder;
+ (ReviveInDungeonResponseProto_Builder*) builderWithPrototype:(ReviveInDungeonResponseProto*) prototype;

+ (ReviveInDungeonResponseProto*) parseFromData:(NSData*) data;
+ (ReviveInDungeonResponseProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReviveInDungeonResponseProto*) parseFromInputStream:(NSInputStream*) input;
+ (ReviveInDungeonResponseProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReviveInDungeonResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReviveInDungeonResponseProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReviveInDungeonResponseProto_Builder : PBGeneratedMessage_Builder {
@private
  ReviveInDungeonResponseProto* result;
}

- (ReviveInDungeonResponseProto*) defaultInstance;

- (ReviveInDungeonResponseProto_Builder*) clear;
- (ReviveInDungeonResponseProto_Builder*) clone;

- (ReviveInDungeonResponseProto*) build;
- (ReviveInDungeonResponseProto*) buildPartial;

- (ReviveInDungeonResponseProto_Builder*) mergeFrom:(ReviveInDungeonResponseProto*) other;
- (ReviveInDungeonResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReviveInDungeonResponseProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSender;
- (MinimumUserProto*) sender;
- (ReviveInDungeonResponseProto_Builder*) setSender:(MinimumUserProto*) value;
- (ReviveInDungeonResponseProto_Builder*) setSenderBuilder:(MinimumUserProto_Builder*) builderForValue;
- (ReviveInDungeonResponseProto_Builder*) mergeSender:(MinimumUserProto*) value;
- (ReviveInDungeonResponseProto_Builder*) clearSender;

- (BOOL) hasStatus;
- (ReviveInDungeonResponseProto_ReviveInDungeonStatus) status;
- (ReviveInDungeonResponseProto_Builder*) setStatus:(ReviveInDungeonResponseProto_ReviveInDungeonStatus) value;
- (ReviveInDungeonResponseProto_Builder*) clearStatus;
@end

